podcast_playlist_names = {
  'https://www.youtube.com/playlist?list=PLdMrbgYfVl-s16D_iT2BJCJ90pWtTO1A4': 'New York Times Podcasts',
  'https://www.youtube.com/playlist?list=PLdMrbgYfVl-s5c4ug8qDCNmdmSKPvr-Pi': 'New York Times - The Interview',
  'https://www.youtube.com/playlist?list=PLdMrbgYfVl-via0c6GiFIzvBEujhy4o2i': 'New York Times - The Headlines',
  'https://www.youtube.com/playlist?list=PLneypbodq-jYq9a6Y8BjobC6KJOIBLCZB': 'Democracy Now Headlines',
  'https://www.youtube.com/playlist?list=PLneypbodq-jb6iEDCsi5QFKv-ACMdZ86s': 'Democracy Now',
  # 'https://www.youtube.com/playlist?list=PLVfJCYRuaJIUNqx6puWYmw7Ug_QsTlA5k': 'Cognitive Revolution',
  'https://www.youtube.com/playlist?list=PLrAXtmErZgOdP_8GztsuKi9nrraNbKKp4': 'Lex Fridman',
  'https://www.youtube.com/playlist?list=PL5PjwSaEJGg6A3LBmWDMXO-xTH4CXoNgE': 'Brain Inspired',
  'https://www.youtube.com/playlist?list=PLYHjB_Comy8RhgQ_JNUbVNEQ6gc4iolhN': 'Bill Simmons NBA',
  'https://www.youtube.com/playlist?list=PLYHjB_Comy8SKByVPadM3Xm0WJQV102Ya': 'Bill Simmons NFL',
  'https://www.youtube.com/playlist?list=PLqQNt9DP_BNC-TM8dJ4EhlTPqD9H6PRD8': 'The Wall Street Journal',
  'https://www.youtube.com/playlist?list=PLqQNt9DP_BNBaIXxT-J1hPynuPVyjbmxY': 'The Wall Street Journal',
  'https://www.youtube.com/playlist?list=PLPNW_gerXa4Pc8S2qoUQc5e8Ir97RLuVW': 'Andrew Huberman',
  'https://www.youtube.com/playlist?list=PLdMrbgYfVl-szepgVpArP0obwYgbKdfvx': 'The Ezra Klein Show',
  # 'https://www.youtube.com/playlist?list=PLHZGTTZG6HcI2tr4tg8oak8_6Wz5on1jY': 'Chomsky\'s Philosophy - Best of Chomsky',
  'https://www.youtube.com/playlist?list=PLM4u6XbiXf5p7irrx8GfeXslWyGB9DGjg': 'a16z Bio',
  'https://www.youtube.com/playlist?list=PLrxfgDEc2NxY_fRExpDXr87tzRbPCaA5x': 'Mindscape Podcast',
  'https://www.youtube.com/playlist?list=PL6ZR-sD5vIlxemueCxB9HLe9I9_K9l5jQ': 'Empire Podcast',
  'https://www.youtube.com/playlist?list=PLS8aEHTqDvpInY9kslUOOK8Qj_-B91o_W': 'Conversation with Tyler',
  'https://www.youtube.com/playlist?list=PLTYmWuFco1_1mHkLh_fKG3OFUFYYel1kw': 'Owen Jones - Palestine',
  'https://www.youtube.com/playlist?list=PLYoqcr7bAIs7kdyMhh-9m4kPLCG6dGAkX': 'The Master Plan',
  'https://www.youtube.com/playlist?list=PLk1Sqn_f33KuWf3tW9BBe_4TP7x8l0m3T': 'Joe Rogan Experience',
  'https://www.youtube.com/playlist?list=PLewmWXyJAGJGTh1O76Aqcazg8oEy9k3Ej': 'The Chris Hedges Report',
  'https://www.youtube.com/playlist?list=PLYa964dzJh1J545AyFlLepb2Prert15te': 'The Tucker Carlson Show',
  'https://www.youtube.com/playlist?list=PL4THPMjF2nCKloPNv7HI-xKRdmH0o_iS1': 'Council on Foreign Relations - The World Next Week',
  'https://www.youtube.com/playlist?list=PLY155lJX6_wcTzyjW2sGB4sTT5ZkivwnN': 'Theo Von - This Past Weekend',
  'https://www.youtube.com/playlist?list=PLn5MTSAqaf8peDZQ57QkJBzewJU1aUokl': 'All In Podcast',
  'https://www.youtube.com/playlist?list=PL1wrt-nxRNK83o9_W8wJvN0y89NmcuLFO': 'Dave Smith - Part of the Problem',
  'https://www.youtube.com/playlist?list=PLTpcK80irdQgz9WLvn1yxFWLXbZw20aV7': 'The Young Turks - Hour 1',
  'https://www.youtube.com/playlist?list=PLTpcK80irdQjwxSkQkLHTvGy2abINHRym': 'The Young Turks - Hour 2',
  'https://www.youtube.com/playlist?list=PLsnSWTCV9wc5nV9PVgeDQ_zFar8jN0nve': 'Dropsite News',
  'https://www.youtube.com/playlist?list=PLS_48r7yuHnsRSghHtImrz-VEAl4hmUKE': 'Glenn Greenwald - System Update',
  'https://www.youtube.com/playlist?list=PLnwt1fUa-EVhHEHY16Za6nORjkefQpR8_': 'AP News - Israel Palestine',
  'https://www.youtube.com/playlist?list=PLDIVi-vBsOExDwCvqcjMvaaKPHw-e_3XA': 'NBC - Chris Hayes',
  'https://www.youtube.com/playlist?list=PLDIVi-vBsOEyETRGoRP9y8zhyu6bHl6iK': 'NBC - Rachel Maddow',
  'https://www.youtube.com/playlist?list=PLDIVi-vBsOEwfv0LML1BGBlPxZsnoa0xM': 'NBC - Ali Vitali',
  'https://www.youtube.com/playlist?list=PLDIVi-vBsOEzOrc-KpytMYuN9zOXB2cd3': 'NBC - Middle East',
  'https://www.youtube.com/playlist?list=PLjOdCQvzbrcGIE4axxNh-ITK2fOA4q3Nb': 'CNN - Amanpour - Middle East',
  'https://www.youtube.com/playlist?list=PLjOdCQvzbrcHHZ_jG9Uld25V0g3NorM-y': 'CNN - Amanpour - International Politics',
  'https://www.youtube.com/playlist?list=PL6XRrncXkMaU55GiCvv416NR2qBD_xbmf': 'CNN - Israel Palestine'
}

podcast_channel_names = {
  'https://www.youtube.com/@RalphNaderRadioHour/videos': 'Ralph Nader Radio Hour',
}