podcast_playlist_names = {
  # mainstream news
  'https://www.youtube.com/playlist?list=PLnwt1fUa-EVhHEHY16Za6nORjkefQpR8_': 'AP News - Israel Palestine',
  'https://www.youtube.com/playlist?list=PLS3XGZxi7cBXnYfJpUas1ud6XATvWATHb': 'BBC - The Latest',
  # 'https://www.youtube.com/playlist?list=PLS3XGZxi7cBVTzEE4Sim9UuNKnUJq9Vkh': 'BBC - World News',
  'https://www.youtube.com/playlist?list=PLDIVi-vBsOExDwCvqcjMvaaKPHw-e_3XA': 'NBC - Chris Hayes',
  'https://www.youtube.com/playlist?list=PLDIVi-vBsOEyETRGoRP9y8zhyu6bHl6iK': 'NBC - Rachel Maddow',
  'https://www.youtube.com/playlist?list=PLDIVi-vBsOEwfv0LML1BGBlPxZsnoa0xM': 'NBC - Ali Vitali',
  'https://www.youtube.com/playlist?list=PLDIVi-vBsOEzOrc-KpytMYuN9zOXB2cd3': 'NBC - Middle East',
  'https://www.youtube.com/playlist?list=PLDIVi-vBsOExUPIUSNzOh4nq3TkXKcwbF': 'MSNBC - The Latest',
  'https://www.youtube.com/playlist?list=PLDIVi-vBsOEzim59VWV9FQjJus3qg_h9-': 'MSNBC - Ayman Mohyeldin',
  'https://www.youtube.com/playlist?list=PLDIVi-vBsOEwnLoiImPnGhZfKvXzTlbee': 'MSNBC - Morning Joe',
  'https://www.youtube.com/playlist?list=PLEb3ThbkPrFbwLLgwnOaB3QXvaTHjskWB': 'CBS - Top News',
  'https://www.youtube.com/playlist?list=PLjOdCQvzbrcGIE4axxNh-ITK2fOA4q3Nb': 'CNN - Amanpour - Middle East',
  'https://www.youtube.com/playlist?list=PLjOdCQvzbrcHHZ_jG9Uld25V0g3NorM-y': 'CNN - Amanpour - International Politics',
  'https://www.youtube.com/playlist?list=PL6XRrncXkMaU55GiCvv416NR2qBD_xbmf': 'CNN - Israel Palestine',
  'https://www.youtube.com/playlist?list=PL6XRrncXkMaVXAutoJ8D2RDKAz_XufaFm': 'CNN - World News',
  'https://www.youtube.com/playlist?list=PLI1yx5Z0Lrv7kEctMwpbBwC6mtWdaiXEH': 'CBS - 60 Minutes',
  'https://www.youtube.com/playlist?list=PLiBCWgmydwnQeRr49qMRGCQpq4ru7zKYB': 'CBS - Face the Nation - Middle East',
  'https://www.youtube.com/playlist?list=PLiBCWgmydwnShGCflEgLOVZIL32dbbdKb': 'CBS - Face the Nation - World News',
  'https://www.youtube.com/playlist?list=PLlTLHnxSVuIyMU4Q4I8NsLAVK1iNANGW9': 'Fox News - Israel Palestine',
  'https://www.youtube.com/playlist?list=PLlTLHnxSVuIyw5jPrLmewrpBJAPYKhgml': 'Fox News - Sean Hannity',
  'https://www.youtube.com/playlist?list=PLlTLHnxSVuIxwOhAhMQY-kHPnms1bpYl7': 'Fox News - Primetime Recap',
  'https://www.youtube.com/playlist?list=PLlTLHnxSVuIycbO7uttsCrmOUpDNFuTbf': 'Fox News - Fox and Friends',
  'https://www.youtube.com/playlist?list=PLlTLHnxSVuIzrARlmz9oCfQEF08UV-v-E': 'Fox News - Tucker Carlson',
  'https://www.youtube.com/playlist?list=PLlTLHnxSVuIzX7sTHBIAEq2ISTvcmhvQJ': 'Fox News - Middle East',
  'https://www.youtube.com/playlist?list=PLlTLHnxSVuIwQgiGlIS9Fd2hUzh4oUqxz': 'Fox News - The Five',
  'https://www.youtube.com/playlist?list=PLdMrbgYfVl-s16D_iT2BJCJ90pWtTO1A4': 'New York Times - The Daily',
  'https://www.youtube.com/playlist?list=PLdMrbgYfVl-szepgVpArP0obwYgbKdfvx': 'New York Times - Ezra Klein',
  'https://www.youtube.com/playlist?list=PLdMrbgYfVl-s5c4ug8qDCNmdmSKPvr-Pi': 'New York Times - The Interview',
  'https://www.youtube.com/playlist?list=PLdMrbgYfVl-via0c6GiFIzvBEujhy4o2i': 'New York Times - The Headlines',
  'https://www.youtube.com/playlist?list=PLo1TdazaYsoqD7pP8cfnydlOTSknnJpAp': 'New Yorker - Radio Hour',
  'https://www.youtube.com/playlist?list=PLp-wXwmbv3z9Xj172jZPPPoYeTS0eanty': 'NPR - News Now',
  'https://www.youtube.com/playlist?list=PLG8IrydigQfccs6PCPMbVnKzrDbdMVBYD': 'Sky News - Israel Palestine',
  'https://www.youtube.com/playlist?list=PLqQNt9DP_BNC-TM8dJ4EhlTPqD9H6PRD8': 'The Wall Street Journal - World News',
  'https://www.youtube.com/playlist?list=PLqQNt9DP_BNBaIXxT-J1hPynuPVyjbmxY': 'The Wall Street Journal - Israel Hamas',
  'https://www.youtube.com/playlist?list=PLqQNt9DP_BND6dwgzxPwouOdQ09A393wP': 'The Wall Street Journal - News Explainers',
  'https://www.youtube.com/playlist?list=PL8QBkS_wk32VzvsrJrmvqlhT_TqPRTllw': 'Washington Post - Israel Palestine',
  # 'https://www.youtube.com/playlist?list=PLqie7QTkNnMbb6RNDLLJT0adUsTYTGNxo': 'The Economic Times - International News',
  'https://www.youtube.com/playlist?list=PLneypbodq-jYq9a6Y8BjobC6KJOIBLCZB': 'Democracy Now Headlines',
  'https://www.youtube.com/playlist?list=PLneypbodq-jb6iEDCsi5QFKv-ACMdZ86s': 'Democracy Now',
  'https://www.youtube.com/playlist?list=PL19Wqzt3FqEVbBVu4OsZ73logsvgHnf3b': 'Carnegie Endowment - Events',
  'https://www.youtube.com/playlist?list=PL19Wqzt3FqEUoEp8lYVqb06rIqT3jkcZi': 'Carnegie Endowment - Middle East',
  # 'https://www.youtube.com/playlist?list=PLVfJCYRuaJIUNqx6puWYmw7Ug_QsTlA5k': 'Cognitive Revolution',
  'https://www.youtube.com/playlist?list=PLrAXtmErZgOdP_8GztsuKi9nrraNbKKp4': 'Lex Fridman',
  'https://www.youtube.com/playlist?list=PL5PjwSaEJGg6A3LBmWDMXO-xTH4CXoNgE': 'Brain Inspired',
  'https://www.youtube.com/playlist?list=PLYHjB_Comy8RhgQ_JNUbVNEQ6gc4iolhN': 'Bill Simmons NBA',
  'https://www.youtube.com/playlist?list=PLYHjB_Comy8SKByVPadM3Xm0WJQV102Ya': 'Bill Simmons NFL',
  'https://www.youtube.com/playlist?list=PLPNW_gerXa4Pc8S2qoUQc5e8Ir97RLuVW': 'Andrew Huberman',
  # 'https://www.youtube.com/playlist?list=PLHZGTTZG6HcI2tr4tg8oak8_6Wz5on1jY': 'Chomsky\'s Philosophy - Best of Chomsky',
  'https://www.youtube.com/playlist?list=PLM4u6XbiXf5p7irrx8GfeXslWyGB9DGjg': 'a16z Bio',
  'https://www.youtube.com/playlist?list=PLUiBUNqvsvrgDDM2V7as8tt7PJCF_wM-x': 'HasanAbi',
  'https://www.youtube.com/playlist?list=PLhHpnycGpC8QZZWtiKn35yHjs42DjqllL': 'Zeteo - Mehdi Unfiltered',
  'https://www.youtube.com/playlist?list=PLrxfgDEc2NxY_fRExpDXr87tzRbPCaA5x': 'Mindscape Podcast',
  'https://www.youtube.com/playlist?list=PLKv2oZZiOAKV4EBTQ56PNqNcURLwgYK2A': 'Martyr Made',
  'https://www.youtube.com/playlist?list=PL6ZR-sD5vIlxemueCxB9HLe9I9_K9l5jQ': 'Empire Podcast',
  'https://www.youtube.com/playlist?list=PLS8aEHTqDvpInY9kslUOOK8Qj_-B91o_W': 'Conversation with Tyler',
  'https://www.youtube.com/playlist?list=PLTYmWuFco1_1mHkLh_fKG3OFUFYYel1kw': 'Owen Jones - Palestine',
  'https://www.youtube.com/playlist?list=PL8RMFyRb2PguHhsO2iYsmzn5v-5SXRv3_': 'The Free Press - Bari Weiss',
  'https://www.youtube.com/playlist?list=PL36GQAccexbwFPOGmbf5pFE32VmyC7ui3': 'MeidasTouch',
  'https://www.youtube.com/playlist?list=PLYoqcr7bAIs7kdyMhh-9m4kPLCG6dGAkX': 'The Master Plan',
  'https://www.youtube.com/playlist?list=PLOC5u3ZE5KnVENyaRfpYQXNVxlfZylJJx': 'The Majority Report - Israel Palestine',
  'https://www.youtube.com/playlist?list=PLk1Sqn_f33KuWf3tW9BBe_4TP7x8l0m3T': 'Joe Rogan Experience',
  'https://www.youtube.com/playlist?list=PLewmWXyJAGJGTh1O76Aqcazg8oEy9k3Ej': 'The Chris Hedges Report',
  'https://www.youtube.com/playlist?list=PLYa964dzJh1J545AyFlLepb2Prert15te': 'The Tucker Carlson Show',
  'https://www.youtube.com/playlist?list=PLPWmUi7FxO4-xBWMrQfjI11vFqFgZN5WC': 'Pod Save the World',
  'https://www.youtube.com/playlist?list=PLq24DlPvfmfpToRu177SwhggAiI8J3dh_': 'Piers Morgan - Israel Palestine',
  'https://www.youtube.com/playlist?list=PLq24DlPvfmfrmuUKXe1yXhiwPhU7TP8Yx': 'Piers Morgan - Big Debates',
  'https://www.youtube.com/playlist?list=PLxQKTUDVHEbSTt5cXhMZtWl5tyR7H5ofT': 'The Megyn Kelly Show',
  'https://www.youtube.com/playlist?list=PL4THPMjF2nCKloPNv7HI-xKRdmH0o_iS1': 'Council on Foreign Relations - The World Next Week',
  'https://www.youtube.com/playlist?list=PL-FNnyGuM4IwUeIltpVHnNQHN6azeVUrN': 'Tarek Masoud - Middle East Dialogue',
  'https://www.youtube.com/playlist?list=PLY155lJX6_wcTzyjW2sGB4sTT5ZkivwnN': 'Theo Von - This Past Weekend',
  'https://www.youtube.com/playlist?list=PLn5MTSAqaf8peDZQ57QkJBzewJU1aUokl': 'All In Podcast',
  'https://www.youtube.com/playlist?list=PL1wrt-nxRNK83o9_W8wJvN0y89NmcuLFO': 'Dave Smith - Part of the Problem',
  'https://www.youtube.com/playlist?list=PLTpcK80irdQgz9WLvn1yxFWLXbZw20aV7': 'The Young Turks - Hour 1',
  'https://www.youtube.com/playlist?list=PLTpcK80irdQjwxSkQkLHTvGy2abINHRym': 'The Young Turks - Hour 2',
  'https://www.youtube.com/playlist?list=PLsnSWTCV9wc5nV9PVgeDQ_zFar8jN0nve': 'Dropsite News',
  'https://www.youtube.com/playlist?list=PLS_48r7yuHnsRSghHtImrz-VEAl4hmUKE': 'Glenn Greenwald - System Update',
  # US Congressmen
  # https://www.youtube.com/@RepAlGreen/videos # Al Green
}

podcast_channel_names = {
  'https://www.youtube.com/@RalphNaderRadioHour/videos': 'Ralph Nader Radio Hour',
  'https://www.youtube.com/@breakingpoints/playlists':   'Breaking Points',
}